name: go-randomy build
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
        id: go
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Test
        shell: msys2 {0}
        run: go test -v
  tag:
    needs: [build]
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version
        if: github.ref == 'refs/heads/master'
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
